module Seeds
  module Electorates
    DATA = [
      50 => [
        {name: "Auckland Central", island: "North Island"},
        {name: "Bay of Plenty", island: "North Island"},
        {name: "Botany", island: "North Island"},
        {name: "Coromandel", island: "North Island"},
        {name: "East Coast", island: "North Island"},
        {name: "East Coast Bays", island: "North Island"},
        {name: "Epsom", island: "North Island"},
        {name: "Hamilton East", island: "North Island"},
        {name: "Hamilton West", island: "North Island"},
        {name: "Hauraki-Waikato", island: "North Island", maori: true},
        {name: "Helensville", island: "North Island"},
        {name: "Hunua", island: "North Island"},
        {name: "Hutt South", island: "North Island"},
        {name: "Ikaroa-Rāwhiti", island: "North Island", maori: true},
        {name: "Mana", island: "North Island"},
        {name: "Māngere", island: "North Island"},
        {name: "Manukau East", island: "North Island"},
        {name: "Manurewa", island: "North Island"},
        {name: "Maungakiekie", island: "North Island"},
        {name: "Mt Albert", island: "North Island"},
        {name: "Mt Roskill", island: "North Island"},
        {name: "Napier", island: "North Island"},
        {name: "New Lynn", island: "North Island"},
        {name: "New Plymouth", island: "North Island"},
        {name: "North Shore", island: "North Island"},
        {name: "Northcote", island: "North Island"},
        {name: "Northland", island: "North Island"},
        {name: "Ōhariu", island: "North Island"},
        {name: "Ōtaki", island: "North Island"},
        {name: "Pakuranga", island: "North Island"},
        {name: "Palmerston North", island: "North Island"},
        {name: "Papakura", island: "North Island"},
        {name: "Rangitīkei", island: "North Island"},
        {name: "Rimutaka", island: "North Island"},
        {name: "Rodney", island: "North Island"},
        {name: "Rongotai", island: "North Island"},
        {name: "Rotorua", island: "North Island"},
        {name: "Tāmaki", island: "North Island"},
        {name: "Tāmaki Makaurau", island: "North Island", maori: true},
        {name: "Taranaki-King Country", island: "North Island"},
        {name: "Taupō", island: "North Island"},
        {name: "Tauranga", island: "North Island"},
        {name: "Te Atatū", island: "North Island"},
        {name: "Te Tai Hauāuru", island: "North Island", maori: true},
        {name: "Te Tai Tokerau", island: "North Island", maori: true},
        {name: "Tukituki", island: "North Island"},
        {name: "Waiariki", island: "North Island", maori: true},
        {name: "Waikato", island: "North Island"},
        {name: "Wairarapa", island: "North Island"},
        {name: "Waitakere", island: "North Island"},
        {name: "Wellington Central", island: "North Island"},
        {name: "Whanganui", island: "North Island"},
        {name: "Whangarei", island: "North Island"},
        {name: "Christchurch Central", island: "South Island"},
        {name: "Christchurch East", island: "South Island"},
        {name: "Clutha-Southland", island: "South Island"},
        {name: "Dunedin North", island: "South Island"},
        {name: "Dunedin South", island: "South Island"},
        {name: "Ilam", island: "South Island"},
        {name: "Invercargill", island: "South Island"},
        {name: "Kaikōura", island: "South Island"},
        {name: "Nelson", island: "South Island"},
        {name: "Port Hills", island: "South Island"},
        {name: "Rangitata", island: "South Island"},
        {name: "Selwyn", island: "South Island"},
        {name: "Te Tai Tonga", island: "South Island", maori: true},
        {name: "Waimakariri", island: "South Island"},
        {name: "Waitaki", island: "South Island"},
        {name: "West Coast-Tasman", island: "South Island"},
        {name: "Wigram", island: "South Island"}
      ]
    ]
  end
end