module Seeds

  module Parliaments

    DATA = [
      {ordinal_number: 1,  majority_party: nil},
      {ordinal_number: 2,  majority_party: nil},
      {ordinal_number: 3,  majority_party: nil},
      {ordinal_number: 4,  majority_party: nil},
      {ordinal_number: 5,  majority_party: nil},
      {ordinal_number: 6,  majority_party: nil},
      {ordinal_number: 7,  majority_party: nil},
      {ordinal_number: 8,  majority_party: nil},
      {ordinal_number: 9,  majority_party: nil},
      {ordinal_number: 10, majority_party: nil},
      {ordinal_number: 11, majority_party: "Liberal Party"},
      {ordinal_number: 12, majority_party: "Liberal Party"},
      {ordinal_number: 13, majority_party: "Liberal Party"},
      {ordinal_number: 14, majority_party: "Liberal Party"},
      {ordinal_number: 15, majority_party: "Liberal Party"},
      {ordinal_number: 16, majority_party: "Liberal Party"},
      {ordinal_number: 17, majority_party: "Liberal Party"},
      {ordinal_number: 18, majority_party: "Reform Party"},
      {ordinal_number: 19, majority_party: "Reform Party"},
      {ordinal_number: 20, majority_party: "Reform Party"},
      {ordinal_number: 21, majority_party: "Reform Party"},
      {ordinal_number: 22, majority_party: "Reform Party"},
      {ordinal_number: 23, majority_party: "United Party"},
      {ordinal_number: 24, majority_party: "Reform Party", coalition: true, 
                           government_parties: ["Reform Party" "United Party"]},
      {ordinal_number: 25, majority_party: "Labour Party"},
      {ordinal_number: 26, majority_party: "Labour Party"},
      {ordinal_number: 27, majority_party: "Labour Party"},
      {ordinal_number: 28, majority_party: "Labour Party"},
      {ordinal_number: 29, majority_party: "National Party"},
      {ordinal_number: 30, majority_party: "National Party"},
      {ordinal_number: 31, majority_party: "National Party"},
      {ordinal_number: 32, majority_party: "Labour Party"},
      {ordinal_number: 33, majority_party: "National Party"},
      {ordinal_number: 34, majority_party: "National Party"},
      {ordinal_number: 35, majority_party: "National Party"},
      {ordinal_number: 36, majority_party: "National Party"},
      {ordinal_number: 37, majority_party: "Labour Party"},
      {ordinal_number: 38, majority_party: "National Party"},
      {ordinal_number: 39, majority_party: "National Party"},
      {ordinal_number: 40, majority_party: "National Party"},
      {ordinal_number: 41, majority_party: "Labour Party"},
      {ordinal_number: 42, majority_party: "Labour Party"},
      {ordinal_number: 43, majority_party: "National Party"},
      {ordinal_number: 44, majority_party: "National Party"},
      {ordinal_number: 45, majority_party: "National Party", minority_government: true,
                           confidence_partners: ["National Party", "ACT Party", "New Zealand First Party"]},
      {ordinal_number: 46, majority_party: "Labour Party", minority_government: true,
                           confidence_partners: ["Labour Party", "Alliance Party", "Green Party"]},
      {ordinal_number: 47, majority_party: "Labour Party", minority_government: true,
                           confidence_partners: ["Labour Party", "Progressives", "United Future Party"]},
      {ordinal_number: 48, majority_party: "Labour Party", minority_government: true,
                           confidence_partners: ["Labour Party", "Progressives", "New Zealand First Party", "United Future Party"]},
      {ordinal_number: 49, majority_party: "National Party", minority_government: true,
                           confidence_partners: ["ACT Party", "United Future Party", "Maori Party"]},
      {ordinal_number: 50, majority_party: "National Party", minority_government: true,
                           confidence_partners: ["ACT Party", "United Future Party", "Maori Party"]}
  ]

  end

end